/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICollection } from "./ICollection";
export type { IERC20Mintable } from "./IERC20Mintable";
export type { IProxiedCollection } from "./IProxiedCollection";
