/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CBCOIN__factory } from "./CBCOIN__factory";
export { Collection__factory } from "./Collection__factory";
export { MockToken__factory } from "./MockToken__factory";
export { ProxiedCollection__factory } from "./ProxiedCollection__factory";
