/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface CollectionRolesInterface extends utils.Interface {
  functions: {
    "COLLECTION_ADMIN_ROLE()": FunctionFragment;
    "LIST_MODERATOR_ROLE()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "COLLECTION_ADMIN_ROLE" | "LIST_MODERATOR_ROLE"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "COLLECTION_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIST_MODERATOR_ROLE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COLLECTION_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIST_MODERATOR_ROLE",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CollectionRoles extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CollectionRolesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    COLLECTION_ADMIN_ROLE(overrides?: CallOverrides): Promise<[number]>;

    LIST_MODERATOR_ROLE(overrides?: CallOverrides): Promise<[number]>;
  };

  COLLECTION_ADMIN_ROLE(overrides?: CallOverrides): Promise<number>;

  LIST_MODERATOR_ROLE(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    COLLECTION_ADMIN_ROLE(overrides?: CallOverrides): Promise<number>;

    LIST_MODERATOR_ROLE(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    COLLECTION_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    LIST_MODERATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    COLLECTION_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    LIST_MODERATOR_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
