/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BrandRoles } from "./BrandRoles";
export type { CollectionRoles } from "./CollectionRoles";
export type { PlatformRoles } from "./PlatformRoles";
