/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BrandRoles,
  BrandRolesInterface,
} from "../../../../../contracts/develompent/access/roles/BrandRoles";

const _abi = [
  {
    inputs: [],
    name: "BRAND_ADMIN_ROLE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BrandRoles__factory {
  static readonly abi = _abi;
  static createInterface(): BrandRolesInterface {
    return new utils.Interface(_abi) as BrandRolesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BrandRoles {
    return new Contract(address, _abi, signerOrProvider) as BrandRoles;
  }
}
