/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CollectionRoles,
  CollectionRolesInterface,
} from "../../../../../contracts/develompent/access/roles/CollectionRoles";

const _abi = [
  {
    inputs: [],
    name: "COLLECTION_ADMIN_ROLE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LIST_MODERATOR_ROLE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CollectionRoles__factory {
  static readonly abi = _abi;
  static createInterface(): CollectionRolesInterface {
    return new utils.Interface(_abi) as CollectionRolesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CollectionRoles {
    return new Contract(address, _abi, signerOrProvider) as CollectionRoles;
  }
}
