/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BrandRoles__factory } from "./BrandRoles__factory";
export { CollectionRoles__factory } from "./CollectionRoles__factory";
export { PlatformRoles__factory } from "./PlatformRoles__factory";
