/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PlatformRoles,
  PlatformRolesInterface,
} from "../../../../../contracts/develompent/access/roles/PlatformRoles";

const _abi = [
  {
    inputs: [],
    name: "CHIEF_ADMIN_ROLE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PLATFORM_ADMIN_ROLE",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class PlatformRoles__factory {
  static readonly abi = _abi;
  static createInterface(): PlatformRolesInterface {
    return new utils.Interface(_abi) as PlatformRolesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PlatformRoles {
    return new Contract(address, _abi, signerOrProvider) as PlatformRoles;
  }
}
