/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICollection__factory } from "./ICollection__factory";
export { IERC20Mintable__factory } from "./IERC20Mintable__factory";
export { IProxiedCollection__factory } from "./IProxiedCollection__factory";
