/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as roles from "./roles";
export type { roles };
export type { Ownable } from "./Ownable";
export type { RolesControl } from "./RolesControl";
export type { Validator } from "./Validator";
