/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFactory,
  IFactoryInterface,
} from "../../../../contracts/develompent/interfaces/IFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_brand",
        type: "string",
      },
      {
        internalType: "address",
        name: "_creator",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_supplyLimit",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "string",
            name: "baseURI",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "whitelist",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "bookingList",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "publicMintTokensLimit",
            type: "uint256",
          },
          {
            internalType: "uint96",
            name: "earnings",
            type: "uint96",
          },
          {
            internalType: "enum ICollectionData.MintStage",
            name: "mintStage",
            type: "uint8",
          },
        ],
        internalType: "struct ICollectionData.CollectionData",
        name: "_data",
        type: "tuple",
      },
    ],
    name: "deployCollection",
    outputs: [
      {
        internalType: "address",
        name: "collection",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryInterface {
    return new utils.Interface(_abi) as IFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFactory {
    return new Contract(address, _abi, signerOrProvider) as IFactory;
  }
}
