/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CBCOIN } from "./CBCOIN";
export type { Collection } from "./Collection";
export type { MockToken } from "./MockToken";
export type { ProxiedCollection } from "./ProxiedCollection";
