/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as roles from "./roles";
export { Ownable__factory } from "./Ownable__factory";
export { RolesControl__factory } from "./RolesControl__factory";
export { Validator__factory } from "./Validator__factory";
